apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-html-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to bloo V1!</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Welcome to bloo V1!</h1>
    <p>This page has been customized for demonstration purposes.</p>
    </body>
    </html>
