apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to bloo V3!</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Welcome to bloo V3!</h1>
    <p>Now with optimized structure!</p>
    </body>
    </html>
