apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4  # Changed from 2 to 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       # Number of additional pods allowed during update
      maxUnavailable: 1 # Number of pods that can be unavailable during update
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
        readinessProbe:   # Added health check
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-html-content
