apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-v1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rohanbundele/argocd-nginx-demo.git
    targetRevision: HEAD
    path: nginx-app/overlays/v1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
